version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todo_db
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todopassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  # backend:
  #   build: ./evro_be_todo
  #   container_name: express_backend
  #   restart: always
  #   depends_on:
  #     - mysql
  #   environment:
  #     DB_HOST: mysql
  #     DB_USER: todo_user
  #     DB_PASSWORD: todopassword
  #     DB_NAME: todo_db
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - ./evro_be_todo:/app
  #   working_dir: /app
  #   command: ["node", "server.js"]

  # frontend:
  #   build: ./evro_fe_todo
  #   container_name: nextjs_frontend
  #   restart: always
  #   depends_on:
  #     - backend
  #   environment:
  #     NEXT_PUBLIC_API_URL: http://backend:5000
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./evro_fe_todo:/app
  #     - /app/node_modules
  #   working_dir: /app
  #   command: ["npm", "run", "dev"]

volumes:
  mysql_data:
