import type { Metadata } from "next";
import "./globals.css";
import { AxiosInterceptor } from "./config/axiosInterceptor";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AxiosInterceptor>
     <html lang="en">
      <body className="flex items-center">
          
          {children}
     
      </body>
    </html>
    </AxiosInterceptor>
  );
}
